services:
  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python blog_project/manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/django_db

volumes:
  postgres_data:
